# Functions

In [29]:
def compute_matchup_stats_Oracle(match):
    s_itt = match["p1 tourney serve adv Oracle"]
    r_itt = match["p1 tourney return adv Oracle"]
    
    s_jtt = match["p2 tourney serve adv Oracle"]
    r_jtt = match["p2 tourney return adv Oracle"]
    
    sg_itt = match["p1 tourney service game adv Oracle"]
    rg_itt = match["p1 tourney return game adv Oracle"]
    
    sg_jtt = match["p2 tourney service game adv Oracle"]
    rg_jtt = match["p2 tourney return game adv Oracle"]
    
    sets_itt = match["p1 tourney set adv Oracle"]
    sets_jtt = match["p2 tourney set adv Oracle"]
    
    t_itt = match["p1 tourney tiebreak adv Oracle"]
    t_jtt = match["p2 tourney tiebreak adv Oracle"]
    
    # Pr[i wins serve on j at tournament t on day t]
    s_ijtt = (s_itt * (1 - r_jtt)) / ((s_itt * (1 - r_jtt)) + (r_jtt * (1 - s_itt)))
    # Pr[j wins serve on i at tournament t on day t]
    s_jitt = (s_jtt * (1 - r_itt)) / ((s_jtt * (1 - r_itt)) + (r_itt * (1 - s_jtt)))
    
    # Pr[i wins service game on j at tournament t on day t]
    sg_ijtt = (sg_itt * (1 - rg_jtt)) / ((sg_itt * (1 - rg_jtt)) + (rg_jtt * (1 - sg_itt)))
    # Pr[j wins service game on i at tournament t on day t]
    sg_jitt = (sg_jtt * (1 - rg_itt)) / ((sg_jtt * (1 - rg_itt)) + (rg_itt * (1 - sg_jtt)))
    
    # Pr[i wins set on j at tournament t on day t]
    sets_ijtt = (sets_itt * (1 - sets_jtt)) / ((sets_itt * (1 - sets_jtt)) + (sets_jtt * (1 - sets_itt)))
    
    # Pr[i wins tiebreak on j at tournament t on day t]
    t_ijtt = (t_itt * (1 - t_jtt)) / ((t_itt * (1 - t_jtt)) + (t_jtt * (1 - t_itt)))
    
    
    return s_ijtt, sg_ijtt, sets_ijtt, t_ijtt, s_jitt, sg_jitt

# T- Oracle Estimator

In [30]:
import pandas as pd
import numpy as np
from datetime import datetime
from dateutil.relativedelta import relativedelta
pd.set_option("display.max_columns", None)

In [31]:
matches = pd.read_csv("./data/JS_shrinkage.csv")
matches["date"] = matches.apply(lambda x: datetime.strptime(x["date"], '%Y-%m-%d'), axis=1)
matches

,pbp_id,date,tny_name,tour,draw,server1,server2,winner,pbp,score,adf_flag,wh_minutes,p1 serves won,p1 serves total,p1 service games won,p1 service games total,p1 sets won,p1 tiebreaks won,p2 serves won,p2 serves total,p2 service games won,p2 service games total,p2 sets won,p2 tiebreaks won,sets total,tourney serves won,tourney serves total,tourney service games won,tourney service games total,p1 serve win rate,p1 return win rate,p1 service game win rate,p1 return game win rate,p1 set win rate,p1 tiebreak win rate,p2 serve win rate,p2 return win rate,p2 service game win rate,p2 return game win rate,p2 set win rate,p2 tiebreak win rate,p1 opp serve win rate,p1 opp return win rate,p1 opp service game win rate,p1 opp return game win rate,p1 opp set win rate,p1 opp tiebreak win rate,p2 opp serve win rate,p2 opp return win rate,p2 opp service game win rate,p2 opp return game win rate,p2 opp set win rate,p2 opp tiebreak win rate,p1 match count,p2 match count,all player year serve win rate,all player year service game win rate,p1 year serve total,p1 year return total,p1 year service game total,p1 year return game total,p1 year set total,p1 year tiebreak total,p2 year serve total,p2 year return total,p2 year service game total,p2 year return game total,p2 year set total,p2 year tiebreak total,p1 year match win rate,p2 year match rate,p1 year match results,p2 year match results,p1 opp match win rate,p2 opp match win rate,tourney sets to win,tourney serve win rate,tourney return win rate,tourney service game win rate,tourney return game win rate,p1 serve win rate variance,p1 return win rate variance,p1 service game win rate variance,p1 return game win rate variance,p1 set win rate variance,p1 tiebreak win rate variance,p2 serve win rate variance,p2 return win rate variance,p2 service game win rate variance,p2 return game win rate variance,p2 set win rate variance,p2 tiebreak win rate variance,all player serve win rate variance,all player return win rate variance,all player service game win rate variance,all player return game win rate variance,all player set win rate variance,all player tiebreak win rate variance,p1 serve win rate variance2,p1 return win rate variance2,p1 service game win rate variance2,p1 return game win rate variance2,p1 set win rate variance2,p1 tiebreak win rate variance2,p2 serve win rate variance2,p2 return win rate variance2,p2 service game win rate variance2,p2 return game win rate variance2,p2 set win rate variance2,p2 tiebreak win rate variance2,all player serve win rate variance2,all player return win rate variance2,all player service game win rate variance2,all player return game win rate variance2,all player set win rate variance2,all player tiebreak win rate variance2,all player serve win rate variance3,all player return win rate variance3,all player service game win rate variance3,all player return game win rate variance3,all player set win rate variance3,all player tiebreak win rate variance3
0,2231275,2011-07-28,ATPStu,ATP,Main,Olivier Rochus,Fabio Fognini,2,SSSS;RRRR;SSRRSS;SSRRSS;RSRSRSRR;SSRSS;RSRRSR;...,6-4 6-1,0,66,27,58,3,9,0,0,32,56,6,8,2,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2231276,2011-07-28,ATPStu,ATP,Main,Robin Haase,Marin Cilic,2,SSRSS;RRSSRSSS;SSSS;RSSSS;SRSRSS;RSRSRSSS;RSRS...,4-6 6-4 6-3,0,141,60,102,11,15,1,0,60,92,12,14,2,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2231342,2011-07-28,Farmer,ATP,Main,Alejandro Falla,Thomaz Bellucci,2,SRRSSRSRRSRSRSRSRSRR;SSSRS;RRSRR;SRSSS;RRSSRR;...,6-0 6-1,0,42,21,55,1,7,0,0,26,37,6,6,2,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2229262,2011-07-28,Credit,ATP,Main,Matthias Bachinger,Julien Benneteau,2,SSSS;SSSS;RRRR;SSSS;SSSS;SRRRSSRSSRRSSRSS;SSSS...,6-4 6-4,0,57,36,59,7,10,0,0,43,58,9,10,2,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2228887,2011-07-28,Credit,ATP,Main,Stan Wawrinka,Peter Luczak,1,SSSS;RRSSSS;SRSSRS;RRSSSS;SSSRS;SSSRRS;RSSSS;R...,6-3 7-5,0,82,43,58,10,11,2,0,34,61,7,10,0,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10782,8628374,2015-12-18,Men'sAustralianOpenWildCardPlayoff,ATP,Main,James Duckworth,Marinko Matosevic,1,SSSS;RSRSRSSS;SSSS;RSSRSS;SRSRRSRR;SRRRSSRR;SS...,4-6 6-3 7-6(7) 7-6(8),0,199,103,154,18,22,3,2,93,146,17,21,1,0,4,564.0,879.0,112.0,147.0,0.635690,0.335260,0.792208,0.169935,0.477612,0.500000,0.575717,0.348559,0.685345,0.188034,0.301887,0.142857,0.625203,0.364778,0.758255,0.178435,0.414046,0.454246,0.629896,0.374191,0.766704,0.191251,0.436469,0.379723,21,19,0.641567,0.797852,2023,1903,308,306,67,20,1499,1423,232,234,53,7,0.210526,0.575717,WWLWLWLWLWWLLWLWLLLLW,LLWLLWLWLLLLLLLLLLW,0.40433,0.450411,3,0.641638,0.358362,0.761905,0.238095,0.000264,0.000194,0.000930,0.000713,0.004855,0.013125,0.000343,0.000301,0.001951,0.000855,0.006920,0.007144,0.000011,0.000009,0.000032,0.00003,0.000144,0.000136,0.000114,0.000121,0.000524,0.000527,0.003731,0.012500,0.000153,0.000162,0.000695,0.000689,0.004717,0.035714,0.005356,0.003533,0.023770,0.009697,0.072589,0.086436,0.003544,0.002968,0.010231,0.009499,0.045352,0.030022
10783,8625517,2015-12-18,Men'sS,ATP,Main,Jesse Huta Galung,Matwe Middelkoop,2,SSRSS;RSSSS;RRRSSR;RRRR;RRSRR;SSRRSRSS;SSRRSS;...,6-4 6-3,0,70,31,54,6,10,0,0,41,65,8,9,2,0,2,461.0,771.0,87.0,124.0,0.621951,0.313187,0.724138,0.100000,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.700937,0.346911,0.829079,0.221165,0.564946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,0.641567,0.797852,164,182,29,30,8,2,0,0,2,2,2,2,NaN,NaN,LL,NaN,NaN,NaN,2,0.597925,0.402075,0.701613,0.298387,0.003110,0.004991,0.000862,0.005156,0.019531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000011,0.000009,0.000032,0.00003,0.000144,0.000136,0.001402,0.001264,0.005562,0.005376,0.031250,0.125000,NaN,NaN,0.080642,0.080642,0.125000,0.125000,0.005356,0.003533,0.023770,0.009697,0.072589,0.086436,0.003544,0.002968,0.010231,0.009499,0.045352,0.030022
10784,8625520,2015-12-18,Men'sS,ATP,Main,Tallon Griekspoor,Robin Haase,2,SSSRS;SSSRRRSS;RSRSSRRR;RSSSS;SRSRRR;SSSRS;SRS...,6-2 6-3,0,63,38,71,5,9,0,0,35,47,8,8,2,0,2,461.0,771.0,87.0,124.0,0.666667,0.520000,0.800000,0.600000,0.750000,NaN,0.622655,0.342847,0.771739,0.186296,0.444444,0.500000,0.480000,0.340000,0.320000,0.160000,0.125000,NaN,0.640685,0.360862,0.791987,0.194391,0.488360,0.409366,1,34,0.641567,0.797852,51,50,10,10,4,2,2878,2838,460,467,99,16,0.411765,0.622655,W,LLLLLLWWLWLLWWLLWWWLWLLWWLLLWLWWLL,NaN,0.484743,2,0.597925,0.402075,0.701613,0.298387,0.226667,0.254694,0.131429,0.268571,0.125000,NaN,0.000141,0.000139,0.000579,0.000439,0.002856,NaN,0.000011,0.000009,0.000032,0.00003,0.000144,0.000136,0.004509,0.004599,0.016128,0.016128,0.062500,0.125000,0.000080,0.000081,0.000351,0.000345,0.002525,0.015625,0.005356,0.003533,0.023770,0.009697,0.072589,0.086436,0.003544,0.002968,0.010231,0.009499,0.045352,0.030022
10785,8632913,2015-12-19,Men'sS,ATP,Main,Jasper Smit,Matwe Middelkoop,2,SRRRR;SSSS;SRRSSS;RRRSSSSS;RSSSS;RRRSR;SRRSRSR...,6-4 6-7(6) 6-3,0,109,62,93,12,15,1,1,68,98,15,16,2,0,3,606.0,1008.0,114.0,160.0,0.675676,0.411111,0.733333,0.333333,0.600000,NaN,0.630769,0.425926,0.818182,0.416667,0.750000,NaN,0.627586,0.314379,0.624000,0.277333,0.342857,NaN,0.610092,0.394737,0.566434,0.076923,0.100000,NaN,1,1,0.641537,0.797829,74,90,15,15,5,2,65,54,11,12,4,2,1.000000,0.630769,W,W,NaN,NaN,2,0.601190,0.398810,0.712500,0.287500,0.222140,0.244819,0.193704,0.231481,0.000000,NaN,0.236538,0.249126,0.116736,0.266975,0.125000,NaN,0.000011,0.000009,0.000032,0.00003,0.000143,0.000136,0.003108,0.002555,0.010753,0.010753,0.050000,0.125000,0.003538,0.004259,0.014663,0.013442,0.062500,0.125000,0.005328,0.003424,0.023732,0.009069,0.072363,0.085721,0.003543,0.002963,0.010226,0.009491,0.045366,0.030110
10786,8634739,2015-12-20,Men'sS,ATP,Main,Matwe Middelkoop,Robin Haase,2,SSSS;SSSS;SRRSRSSS;SSRRRSRSSS;SSRSRS;SRSSS;RSS...,7-6(4) 2-6 7-5,0,121,63,97,13,16,1,0,69,112,12,16,2,1,3,736.0,1199.0,141.0,191.0,0.668712,0.367347,0.888889,0.296296,0.714286,0.333333,0.624615,0.345823,0.775641,0.191176,0.455446,0.500000,0.646506,0.382594,0.685090,0.148883,0.271429,0.222222,0.639874,0.358384,0.790144,0.196318,0.488591,0.409366,2,35,0.641555,0.797863,163,147,27,27,7,3,2925,2909,468,476,101,16,0.428571,0.624615,WW,LLLLLLWWLWLLWWLLWWWLWLLWWLLLWLWWLLW,0.25000,0.485179,2,0.613845,0.386155,0.738220,0.261780,0.000916,0.001852,0.001660,0.008675,0.014161,0.024691,0.000140,0.000140,0.000572,0.000446,0.002859,0.010723,0.000011,0.000009,0.000032,0.00003,0.000143,0.000136,0.001411,0.001564,0.005973,0.005973,0.035714,0.083333,0.000079,0.000079,0.000345,0.000339,0.002475,0.015625,0.005330,0.003400,0.023756,0.008930,0.071769,0.087201,0.003538,0.002961,0.010213,0.009484,0.045328,0.030350

### Compute Oracle Estimator coef $\frac{v^2}{v^2 + (T - \sigma)^2}$ using clusted variance by match

In [32]:
matches["p1 oracle coef serve"] = matches["p1 serve win rate variance"] / (matches["p1 serve win rate variance"] + (matches["all player year serve win rate"] - matches["p1 serve win rate"])**2)
matches["p1 oracle coef return"] = matches["p1 return win rate variance"] / (matches["p1 return win rate variance"] + ((1 - matches["all player year serve win rate"]) - matches["p1 return win rate"])**2)
matches["p1 oracle coef service game"] = matches["p1 service game win rate variance"] / (matches["p1 service game win rate variance"] + (matches["all player year service game win rate"] - matches["p1 service game win rate"])**2)
matches["p1 oracle coef return game"] = matches["p1 return game win rate variance"] / (matches["p1 return game win rate variance"] + ((1 - matches["all player year service game win rate"]) - matches["p1 return game win rate"])**2)
matches["p1 oracle coef set"] = matches["p1 set win rate variance"] / (matches["p1 set win rate variance"] + (0.5 - matches["p1 set win rate"])**2)
matches["p1 oracle coef tiebreak"] = matches["p1 tiebreak win rate variance"] / (matches["p1 tiebreak win rate variance"] + (0.5 - matches["p1 tiebreak win rate"])**2)

matches["p2 oracle coef serve"] = matches["p2 serve win rate variance"] / (matches["p2 serve win rate variance"] + (matches["all player year serve win rate"] - matches["p2 serve win rate"])**2)
matches["p2 oracle coef return"] = matches["p2 return win rate variance"] / (matches["p2 return win rate variance"] + ((1 - matches["all player year serve win rate"]) - matches["p2 return win rate"])**2)
matches["p2 oracle coef service game"] = matches["p2 service game win rate variance"] / (matches["p2 service game win rate variance"] + (matches["all player year service game win rate"] - matches["p2 service game win rate"])**2)
matches["p2 oracle coef return game"] = matches["p2 return game win rate variance"] / (matches["p2 return game win rate variance"] + ((1 - matches["all player year service game win rate"]) - matches["p2 return game win rate"])**2)
matches["p2 oracle coef set"] = matches["p2 set win rate variance"] / (matches["p2 set win rate variance"] + (0.5 - matches["p2 set win rate"])**2)
matches["p2 oracle coef tiebreak"] = matches["p2 tiebreak win rate variance"] / (matches["p2 tiebreak win rate variance"] + (0.5 - matches["p2 tiebreak win rate"])**2)

### Compute Oracle Estimator coef $\frac{v^2}{v^2 + (T - \sigma)^2}$ using pooled variance dividing by number of attempts

In [33]:
matches["p1 oracle coef serve2"] = matches["p1 serve win rate variance2"] / (matches["p1 serve win rate variance2"] + (matches["all player year serve win rate"] - matches["p1 serve win rate"])**2)
matches["p1 oracle coef return2"] = matches["p1 return win rate variance2"] / (matches["p1 return win rate variance2"] + ((1 - matches["all player year serve win rate"]) - matches["p1 return win rate"])**2)
matches["p1 oracle coef service game2"] = matches["p1 service game win rate variance2"] / (matches["p1 service game win rate variance2"] + (matches["all player year service game win rate"] - matches["p1 service game win rate"])**2)
matches["p1 oracle coef return game2"] = matches["p1 return game win rate variance2"] / (matches["p1 return game win rate variance2"] + ((1 - matches["all player year service game win rate"]) - matches["p1 return game win rate"])**2)
matches["p1 oracle coef set2"] = matches["p1 set win rate variance2"] / (matches["p1 set win rate variance2"] + (0.5 - matches["p1 set win rate"])**2)
matches["p1 oracle coef tiebreak2"] = matches["p1 tiebreak win rate variance2"] / (matches["p1 tiebreak win rate variance2"] + (0.5 - matches["p1 tiebreak win rate"])**2)

matches["p2 oracle coef serve2"] = matches["p2 serve win rate variance2"] / (matches["p2 serve win rate variance2"] + (matches["all player year serve win rate"] - matches["p2 serve win rate"])**2)
matches["p2 oracle coef return2"] = matches["p2 return win rate variance2"] / (matches["p2 return win rate variance2"] + ((1 - matches["all player year serve win rate"]) - matches["p2 return win rate"])**2)
matches["p2 oracle coef service game2"] = matches["p2 service game win rate variance2"] / (matches["p2 service game win rate variance2"] + (matches["all player year service game win rate"] - matches["p2 service game win rate"])**2)
matches["p2 oracle coef return game2"] = matches["p2 return game win rate variance2"] / (matches["p2 return game win rate variance2"] + ((1 - matches["all player year service game win rate"]) - matches["p2 return game win rate"])**2)
matches["p2 oracle coef set2"] = matches["p2 set win rate variance2"] / (matches["p2 set win rate variance2"] + (0.5 - matches["p2 set win rate"])**2)
matches["p2 oracle coef tiebreak2"] = matches["p2 tiebreak win rate variance2"] / (matches["p2 tiebreak win rate variance2"] + (0.5 - matches["p2 tiebreak win rate"])**2)

### Compute Oracle Shrunken rates using coefs1

In [34]:
matches["p1 serve win rate Oracle"] = matches["p1 serve win rate"] - matches["p1 oracle coef serve"] * (matches["p1 serve win rate"] - matches["all player year serve win rate"])
matches["p1 return win rate Oracle"] = matches["p1 return win rate"] - matches["p1 oracle coef return"] * (matches["p1 return win rate"] - (1 - matches["all player year serve win rate"]))
matches["p1 service game win rate Oracle"] = matches["p1 service game win rate"] - matches["p1 oracle coef service game"] * (matches["p1 service game win rate"] - matches["all player year service game win rate"])
matches["p1 return game win rate Oracle"] = matches["p1 return game win rate"] - matches["p1 oracle coef return game"] * (matches["p1 return game win rate"] - (1 - matches["all player year service game win rate"]))
matches["p1 set win rate Oracle"] = matches["p1 set win rate"] - matches["p1 oracle coef set"] * (matches["p1 set win rate"] - 0.5)
matches["p1 tiebreak win rate Oracle"] = matches["p1 tiebreak win rate"] - matches["p1 oracle coef tiebreak"] * (matches["p1 tiebreak win rate"] - 0.5)

matches["p2 serve win rate Oracle"] = matches["p2 serve win rate"] - matches["p2 oracle coef serve"] * (matches["p2 serve win rate"] - matches["all player year serve win rate"])
matches["p2 return win rate Oracle"] = matches["p2 return win rate"] - matches["p2 oracle coef return"] * (matches["p2 return win rate"] - (1 - matches["all player year serve win rate"]))
matches["p2 service game win rate Oracle"] = matches["p2 service game win rate"] - matches["p2 oracle coef service game"] * (matches["p2 service game win rate"] - matches["all player year service game win rate"])
matches["p2 return game win rate Oracle"] = matches["p2 return game win rate"] - matches["p2 oracle coef return game"] * (matches["p2 return game win rate"] - (1 - matches["all player year service game win rate"]))
matches["p2 set win rate Oracle"] = matches["p2 set win rate"] - matches["p2 oracle coef set"] * (matches["p2 set win rate"] - 0.5)
matches["p2 tiebreak win rate Oracle"] = matches["p2 tiebreak win rate"] - matches["p2 oracle coef tiebreak"] * (matches["p2 tiebreak win rate"] - 0.5)

In [45]:
# calculate no sos adjust p1 serve_tt, pl_service_game_tt, etc.
matches["p1 serve_tt Oracle no sos adjust"] = (matches["p1 serve win rate Oracle"] * (1 - matches["p2 return win rate Oracle"])) / ((matches["p1 serve win rate Oracle"] * (1 - matches["p2 return win rate Oracle"])) + (matches["p2 return win rate Oracle"] * (1 - matches["p1 serve win rate Oracle"])))
matches["p2 serve_tt Oracle no sos adjust"] = (matches["p2 serve win rate Oracle"] * (1 - matches["p1 return win rate Oracle"])) / ((matches["p2 serve win rate Oracle"] * (1 - matches["p1 return win rate Oracle"])) + (matches["p1 return win rate Oracle"] * (1 - matches["p2 serve win rate Oracle"])))

matches["p1 service_game_tt Oracle no sos adjust"] = (matches["p1 service game win rate Oracle"] * (1 - matches["p2 return game win rate Oracle"])) / ((matches["p1 service game win rate Oracle"] * (1 - matches["p2 return game win rate Oracle"])) + (matches["p2 return game win rate Oracle"] * (1 - matches["p1 service game win rate Oracle"])))
matches["p2 service_game_tt Oracle no sos adjust"] = (matches["p2 service game win rate Oracle"] * (1 - matches["p1 return game win rate Oracle"])) / ((matches["p2 service game win rate Oracle"] * (1 - matches["p1 return game win rate Oracle"])) + (matches["p1 return game win rate Oracle"] * (1 - matches["p2 service game win rate Oracle"])))

matches["p1 tiebreak_tt Oracle no sos adjust"] = (matches["p1 tiebreak win rate Oracle"] * (1 - matches["p2 tiebreak win rate Oracle"])) / ((matches["p1 tiebreak win rate Oracle"] * (1 - matches["p2 tiebreak win rate Oracle"])) + (matches["p2 tiebreak win rate Oracle"] * (1 - matches["p1 tiebreak win rate Oracle"])))

matches["p1 set_tt Oracle no sos adjust"] = (matches["p1 set win rate Oracle"] * (1 - matches["p2 set win rate Oracle"])) / ((matches["p1 set win rate Oracle"] * (1 - matches["p2 set win rate Oracle"])) + (matches["p2 set win rate Oracle"] * (1 - matches["p1 set win rate Oracle"])))

In [46]:
# Generate relative abilities JS, we use unshrunken opp stats (allows a possibility for improvement)
matches["p1 relative serve Oracle"] = matches["p1 serve win rate Oracle"] - (1 - matches["p1 opp return win rate"])
matches["p2 relative serve Oracle"] = matches["p2 serve win rate Oracle"] - (1 - matches["p2 opp return win rate"])

matches["p1 relative return Oracle"] = matches["p1 return win rate Oracle"] - (1 - matches["p1 opp serve win rate"])
matches["p2 relative return Oracle"] = matches["p2 return win rate Oracle"] - (1 - matches["p2 opp serve win rate"])

matches["p1 relative service games Oracle"] = matches["p1 service game win rate Oracle"] - (1 - matches["p1 opp return game win rate"])
matches["p2 relative service games Oracle"] = matches["p2 service game win rate Oracle"] - (1 - matches["p2 opp return game win rate"])

matches["p1 relative return games Oracle"] = matches["p1 return game win rate Oracle"] - (1 - matches["p1 opp service game win rate"])
matches["p2 relative return games Oracle"] = matches["p2 return game win rate Oracle"] - (1 - matches["p2 opp service game win rate"])

matches["p1 relative set Oracle"] = matches["p1 set win rate Oracle"] - (1 - matches["p1 opp set win rate"])
matches["p2 relative set Oracle"] = matches["p2 set win rate Oracle"] - (1 - matches["p2 opp set win rate"])

matches["p1 relative tiebreak Oracle"] = matches["p1 tiebreak win rate Oracle"] - (1 - matches["p1 opp tiebreak win rate"])
matches["p2 relative tiebreak Oracle"] = matches["p2 tiebreak win rate Oracle"] - (1 - matches["p2 opp tiebreak win rate"])

In [47]:
# Computing player-tournament stats
matches["p1 tourney serve adv Oracle"] = (matches["tourney serve win rate"] + matches["p1 relative serve Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p1 tourney return adv Oracle"] = (matches["tourney return win rate"] + matches["p1 relative return Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney serve adv Oracle"] = (matches["tourney serve win rate"] + matches["p2 relative serve Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney return adv Oracle"] = (matches["tourney return win rate"] + matches["p2 relative return Oracle"]).clip(upper=0.9985, lower=0.0015)

matches["p1 tourney service game adv Oracle"] = (matches["tourney service game win rate"] + matches["p1 relative service games Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p1 tourney return game adv Oracle"] = (matches["tourney return game win rate"] + matches["p1 relative return games Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney service game adv Oracle"] = (matches["tourney service game win rate"] + matches["p2 relative service games Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney return game adv Oracle"] = (matches["tourney return game win rate"] + matches["p2 relative return games Oracle"]).clip(upper=0.9985, lower=0.0015)

matches["p1 tourney set adv Oracle"] = (0.5 + matches["p1 relative set Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney set adv Oracle"] = (0.5 + matches["p2 relative set Oracle"]).clip(upper=0.9985, lower=0.0015)

matches["p1 tourney tiebreak adv Oracle"] = (0.5 + matches["p1 relative tiebreak Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney tiebreak adv Oracle"] = (0.5 + matches["p2 relative tiebreak Oracle"]).clip(upper=0.9985, lower=0.0015)

In [48]:
# Computing matchup statistics
matchup_cols = ["p1 serve_tt", "p1 service_game_tt", "p1 set_tt", "p1 tiebreak_tt", "p2 serve_tt", "p2 service_game_tt"]
matches[matchup_cols] = matches.apply(lambda match: compute_matchup_stats_Oracle(match), axis=1, result_type="expand")

### Predict using $s_{ijtt}$ and $r_{ijtt}$

In [49]:
# Filter matches we want to predict on

# Only consider matches on or after August 1, 2012, because we've had one year of data at that point
games_after_2012 = matches[matches["date"] > datetime.strptime("01 Aug 12", '%d %b %y')]

# Only consider best of three set matches
games_after_2012 = games_after_2012[games_after_2012["tourney sets to win"] == 2]

# Don't consider Davis Cup matches because they don't have a final set tiebreak
games_after_2012 = games_after_2012[games_after_2012["tny_name"] != "DavisC"]

# Remove rows where either player hasn't played at least 10 matches in the past year
games_after_2012 = games_after_2012[(games_after_2012["p1 match count"] >= 2) & (games_after_2012["p2 match count"] >= 2)]

In [50]:
# Remove rows where we don't have s_ijtt values to predict the result of the match
games_after_2012 = games_after_2012[(games_after_2012['p1 serve_tt'].notna()) & (games_after_2012['p2 serve_tt'].notna())]

In [51]:
# import the markov model functions lazily
%run Modeling_tennis_match_iid_points.ipynb

0.69924
0.933836

In [52]:
# compute Pr[p1 wins] with opponent/ tournament adjusted shrunken serve values
games_after_2012["p1 pr win"] = games_after_2012.apply(lambda match: match_driver(2, 6, 4, 7, 1, match["p1 serve_tt"], match["p2 serve_tt"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [53]:
# compute Pr[p1 wins] with non sos adjusted JS serve rates
games_after_2012["p1 pr win Oracle no sos adjust"] = games_after_2012.apply(lambda match: match_driver(2, 6, 4, 7, 1, match["p1 serve_tt Oracle no sos adjust"], match["p2 serve_tt Oracle no sos adjust"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [54]:
# compute log loss
games_after_2012["winner"] = games_after_2012["winner"].replace(2,0)

compute_lloss = games_after_2012[["winner", "p1 pr win", "p1 pr win Oracle no sos adjust"]]

compute_lloss["lloss sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win"]) + (1-m["winner"])*np.log(1 - m["p1 pr win"])), axis=1)
compute_lloss["lloss no sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win Oracle no sos adjust"]) + (1-m["winner"])*np.log(1 - m["p1 pr win Oracle no sos adjust"])), axis=1)
N = compute_lloss.shape[0]

lloss_sos_adjust = (compute_lloss["lloss sos adjust"].sum()) * (-1/N)
lloss_no_sos_adjust = (compute_lloss["lloss no sos adjust"].sum()) * (-1/N)

print(f"Sos adjust log loss: {lloss_sos_adjust}")
print(f"No sos adjust log loss: {lloss_no_sos_adjust}")
print(f"Random guessing log loss: {-np.log(0.5)}")

Sos adjust log loss: 0.6294165892892446
No sos adjust log loss: 0.6348029525469211
Random guessing log loss: 0.6931471805599453

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

### Predict using $sg_{ijtt}$ and $rg_{ijtt}$ and $t_{ijtt}$

In [55]:
# Filter matches we want to predict on

# Only consider matches on or after August 1, 2012, because we've had one year of data at that point
games_after_2012 = matches[matches["date"] > datetime.strptime("01 Aug 12", '%d %b %y')]

# Only consider best of three set matches
games_after_2012 = games_after_2012[games_after_2012["tourney sets to win"] == 2]

# Don't consider Davis Cup matches because they don't have a final set tiebreak
games_after_2012 = games_after_2012[games_after_2012["tny_name"] != "DavisC"]

# Remove rows where either player hasn't played at least 10 matches in the past year
games_after_2012 = games_after_2012[(games_after_2012["p1 match count"] >= 2) & (games_after_2012["p2 match count"] >= 2)]

In [56]:
# Remove rows where we don't have sg_ijtt and t_ijtt values to predict the result of the match
games_after_2012 = games_after_2012[(games_after_2012['p1 service_game_tt'].notna()) & (games_after_2012['p2 service_game_tt'].notna()) & (games_after_2012['p1 tiebreak_tt'].notna())]

In [57]:

# compute Pr[p1 wins] with non opponenent/ tournament adjusted service game values
games_after_2012["p1 pr win opp adjust game based"] = games_after_2012.apply(lambda match: match_driver_game_based(2, 6, 4, 7, 1, match["p1 service_game_tt"], match["p2 service_game_tt"], match["p1 tiebreak_tt"]), axis=1).clip(upper=0.9985, lower=0.0015)
games_after_2012["p1 pr win Oracle no sos adjust game based"] = games_after_2012.apply(lambda match: match_driver_game_based(2, 6, 4, 7, 1, match["p1 service_game_tt Oracle no sos adjust"], match["p2 service_game_tt Oracle no sos adjust"], match["p1 tiebreak_tt Oracle no sos adjust"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [58]:
games_after_2012["winner"] = games_after_2012["winner"].replace(2,0)

compute_lloss = games_after_2012[["winner", "p1 pr win opp adjust game based", "p1 pr win Oracle no sos adjust game based"]]

compute_lloss["lloss sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win opp adjust game based"]) + (1-m["winner"])*np.log(1 - m["p1 pr win opp adjust game based"])), axis=1)
compute_lloss["lloss Oracle no sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win Oracle no sos adjust game based"]) + (1-m["winner"])*np.log(1 - m["p1 pr win Oracle no sos adjust game based"])), axis=1)
N = compute_lloss.shape[0]

lloss_sos_adjust = (compute_lloss["lloss sos adjust"].sum()) * (-1/N)
lloss_no_sos_adjust = (compute_lloss["lloss Oracle no sos adjust"].sum()) * (-1/N)

print(f"Sos adjust log loss: {lloss_sos_adjust}")
print(f"No sos adjust log loss: {lloss_no_sos_adjust}")
print(f"Random guessing log loss: {-np.log(0.5)}")

Sos adjust log loss: 0.6233441522009079
No sos adjust log loss: 0.6404255205075456
Random guessing log loss: 0.6931471805599453

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Try to predict games using $sets_{ijtt}$ values

In [59]:
# Filter matches we want to predict on

# Only consider matches on or after August 1, 2012, because we've had one year of data at that point
games_after_2012 = matches[matches["date"] > datetime.strptime("01 Aug 12", '%d %b %y')]

# Only consider best of three set matches
games_after_2012 = games_after_2012[games_after_2012["tourney sets to win"] == 2]

# Don't consider Davis Cup matches because they don't have a final set tiebreak
games_after_2012 = games_after_2012[games_after_2012["tny_name"] != "DavisC"]

# Remove rows where either player hasn't played at least 10 matches in the past year
games_after_2012 = games_after_2012[(games_after_2012["p1 match count"] >= 2) & (games_after_2012["p2 match count"] >= 2)]

In [60]:
# Remove rows where we don't have sg_ijtt and t_ijtt values to predict the result of the match
games_after_2012 = games_after_2012[(games_after_2012['p1 set_tt'].notna())]

In [61]:

# compute Pr[p1 wins] with non opponenent/ tournament adjusted service game values
games_after_2012["p1 pr win opp adjust set based"] = games_after_2012.apply(lambda match: match_driver_set_based(2, match["p1 set_tt"]), axis=1).clip(upper=0.9985, lower=0.0015)
games_after_2012["p1 pr win Oracle no sos adjust set based"] = games_after_2012.apply(lambda match: match_driver_set_based(2, match["p1 set_tt Oracle no sos adjust"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [62]:
games_after_2012["winner"] = games_after_2012["winner"].replace(2,0)

compute_lloss = games_after_2012[["winner", "p1 pr win opp adjust set based", "p1 pr win Oracle no sos adjust set based"]]

compute_lloss["lloss sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win opp adjust set based"]) + (1-m["winner"])*np.log(1 - m["p1 pr win opp adjust set based"])), axis=1)
compute_lloss["lloss no sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win Oracle no sos adjust set based"]) + (1-m["winner"])*np.log(1 - m["p1 pr win Oracle no sos adjust set based"])), axis=1)
N = compute_lloss.shape[0]

lloss_sos_adjust = (compute_lloss["lloss sos adjust"].sum()) * (-1/N)
lloss_no_sos_adjust = (compute_lloss["lloss no sos adjust"].sum()) * (-1/N)

print(f"Sos adjust log loss: {lloss_sos_adjust}")
print(f"No sos adjust log loss: {lloss_no_sos_adjust}")
print(f"Random guessing log loss: {-np.log(0.5)}")

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

Sos adjust log loss: 0.6251465503542543
No sos adjust log loss: 0.6354109498602519
Random guessing log loss: 0.6931471805599453

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Try to predict using $sg_{ijtt}$ for games and $s_{ijtt}, s_{jitt}$ for tiebreaks

In [63]:
# Filter matches we want to predict on

# Only consider matches on or after August 1, 2012, because we've had one year of data at that point
games_after_2012 = matches[matches["date"] > datetime.strptime("01 Aug 12", '%d %b %y')]

# Only consider best of three set matches
games_after_2012 = games_after_2012[games_after_2012["tourney sets to win"] == 2]

# Don't consider Davis Cup matches because they don't have a final set tiebreak
games_after_2012 = games_after_2012[games_after_2012["tny_name"] != "DavisC"]

# Remove rows where either player hasn't played at least 10 matches in the past year
games_after_2012 = games_after_2012[(games_after_2012["p1 match count"] >= 2) & (games_after_2012["p2 match count"] >= 2)]

In [64]:
# Remove rows where we don't have sg_ijtt and s_ijtt values to predict the result of the match
games_after_2012 = games_after_2012[(games_after_2012['p1 service_game_tt'].notna()) & (games_after_2012['p2 service_game_tt'].notna()) & (games_after_2012['p1 serve_tt'].notna()) & (games_after_2012['p2 serve_tt'].notna())]

In [65]:
# compute Pr[p1 wins] with non opponenent/ tournament adjusted service game values
games_after_2012["p1 pr win opp adjust mix"] = games_after_2012.apply(lambda match: match_driver_game_based_tiebreak_serve_based(2, 6, 4, 7, 1, match["p1 service_game_tt"], match["p2 service_game_tt"], match["p1 serve_tt"], match["p2 serve_tt"]), axis=1).clip(upper=0.9985, lower=0.0015)
games_after_2012["p1 pr win Oracle no sos adjust mix"] = games_after_2012.apply(lambda match: match_driver_game_based_tiebreak_serve_based(2, 6, 4, 7, 1, match["p1 service_game_tt Oracle no sos adjust"], match["p2 service_game_tt Oracle no sos adjust"], match["p1 serve_tt Oracle no sos adjust"], match["p2 serve_tt Oracle no sos adjust"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [67]:
games_after_2012["winner"] = games_after_2012["winner"].replace(2,0)

compute_lloss = games_after_2012[["winner", "p1 pr win opp adjust mix", "p1 pr win Oracle no sos adjust mix"]]

compute_lloss["lloss sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win opp adjust mix"]) + (1-m["winner"])*np.log(1 - m["p1 pr win opp adjust mix"])), axis=1)
compute_lloss["lloss no sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win Oracle no sos adjust mix"]) + (1-m["winner"])*np.log(1 - m["p1 pr win Oracle no sos adjust mix"])), axis=1)
N = compute_lloss.shape[0]

lloss_sos_adjust = (compute_lloss["lloss sos adjust"].sum()) * (-1/N)
lloss_no_sos_adjust = (compute_lloss["lloss no sos adjust"].sum()) * (-1/N)

print(f"Sos adjust log loss: {lloss_sos_adjust}")
print(f"No sos adjust log loss: {lloss_no_sos_adjust}")
print(f"Random guessing log loss: {-np.log(0.5)}")

Sos adjust log loss: 0.6181584193879613
No sos adjust log loss: 0.6335536322108394
Random guessing log loss: 0.6931471805599453

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Compute Oracle Shrunken rates using coefs2

In [68]:
matches["p1 serve win rate Oracle"] = matches["p1 serve win rate"] - matches["p1 oracle coef serve2"] * (matches["p1 serve win rate"] - matches["all player year serve win rate"])
matches["p1 return win rate Oracle"] = matches["p1 return win rate"] - matches["p1 oracle coef return2"] * (matches["p1 return win rate"] - (1 - matches["all player year serve win rate"]))
matches["p1 service game win rate Oracle"] = matches["p1 service game win rate"] - matches["p1 oracle coef service game2"] * (matches["p1 service game win rate"] - matches["all player year service game win rate"])
matches["p1 return game win rate Oracle"] = matches["p1 return game win rate"] - matches["p1 oracle coef return game2"] * (matches["p1 return game win rate"] - (1 - matches["all player year service game win rate"]))
matches["p1 set win rate Oracle"] = matches["p1 set win rate"] - matches["p1 oracle coef set2"] * (matches["p1 set win rate"] - 0.5)
matches["p1 tiebreak win rate Oracle"] = matches["p1 tiebreak win rate"] - matches["p1 oracle coef tiebreak2"] * (matches["p1 tiebreak win rate"] - 0.5)

matches["p2 serve win rate Oracle"] = matches["p2 serve win rate"] - matches["p2 oracle coef serve2"] * (matches["p2 serve win rate"] - matches["all player year serve win rate"])
matches["p2 return win rate Oracle"] = matches["p2 return win rate"] - matches["p2 oracle coef return2"] * (matches["p2 return win rate"] - (1 - matches["all player year serve win rate"]))
matches["p2 service game win rate Oracle"] = matches["p2 service game win rate"] - matches["p2 oracle coef service game2"] * (matches["p2 service game win rate"] - matches["all player year service game win rate"])
matches["p2 return game win rate Oracle"] = matches["p2 return game win rate"] - matches["p2 oracle coef return game2"] * (matches["p2 return game win rate"] - (1 - matches["all player year service game win rate"]))
matches["p2 set win rate Oracle"] = matches["p2 set win rate"] - matches["p2 oracle coef set2"] * (matches["p2 set win rate"] - 0.5)
matches["p2 tiebreak win rate Oracle"] = matches["p2 tiebreak win rate"] - matches["p2 oracle coef tiebreak2"] * (matches["p2 tiebreak win rate"] - 0.5)

In [69]:
# calculate no sos adjust p1 serve_tt, pl_service_game_tt, etc.
matches["p1 serve_tt Oracle no sos adjust"] = (matches["p1 serve win rate Oracle"] * (1 - matches["p2 return win rate Oracle"])) / ((matches["p1 serve win rate Oracle"] * (1 - matches["p2 return win rate Oracle"])) + (matches["p2 return win rate Oracle"] * (1 - matches["p1 serve win rate Oracle"])))
matches["p2 serve_tt Oracle no sos adjust"] = (matches["p2 serve win rate Oracle"] * (1 - matches["p1 return win rate Oracle"])) / ((matches["p2 serve win rate Oracle"] * (1 - matches["p1 return win rate Oracle"])) + (matches["p1 return win rate Oracle"] * (1 - matches["p2 serve win rate Oracle"])))

matches["p1 service_game_tt Oracle no sos adjust"] = (matches["p1 service game win rate Oracle"] * (1 - matches["p2 return game win rate Oracle"])) / ((matches["p1 service game win rate Oracle"] * (1 - matches["p2 return game win rate Oracle"])) + (matches["p2 return game win rate Oracle"] * (1 - matches["p1 service game win rate Oracle"])))
matches["p2 service_game_tt Oracle no sos adjust"] = (matches["p2 service game win rate Oracle"] * (1 - matches["p1 return game win rate Oracle"])) / ((matches["p2 service game win rate Oracle"] * (1 - matches["p1 return game win rate Oracle"])) + (matches["p1 return game win rate Oracle"] * (1 - matches["p2 service game win rate Oracle"])))

matches["p1 tiebreak_tt Oracle no sos adjust"] = (matches["p1 tiebreak win rate Oracle"] * (1 - matches["p2 tiebreak win rate Oracle"])) / ((matches["p1 tiebreak win rate Oracle"] * (1 - matches["p2 tiebreak win rate Oracle"])) + (matches["p2 tiebreak win rate Oracle"] * (1 - matches["p1 tiebreak win rate Oracle"])))

matches["p1 set_tt Oracle no sos adjust"] = (matches["p1 set win rate Oracle"] * (1 - matches["p2 set win rate Oracle"])) / ((matches["p1 set win rate Oracle"] * (1 - matches["p2 set win rate Oracle"])) + (matches["p2 set win rate Oracle"] * (1 - matches["p1 set win rate Oracle"])))

In [70]:
# Generate relative abilities JS, we use unshrunken opp stats (allows a possibility for improvement)
matches["p1 relative serve Oracle"] = matches["p1 serve win rate Oracle"] - (1 - matches["p1 opp return win rate"])
matches["p2 relative serve Oracle"] = matches["p2 serve win rate Oracle"] - (1 - matches["p2 opp return win rate"])

matches["p1 relative return Oracle"] = matches["p1 return win rate Oracle"] - (1 - matches["p1 opp serve win rate"])
matches["p2 relative return Oracle"] = matches["p2 return win rate Oracle"] - (1 - matches["p2 opp serve win rate"])

matches["p1 relative service games Oracle"] = matches["p1 service game win rate Oracle"] - (1 - matches["p1 opp return game win rate"])
matches["p2 relative service games Oracle"] = matches["p2 service game win rate Oracle"] - (1 - matches["p2 opp return game win rate"])

matches["p1 relative return games Oracle"] = matches["p1 return game win rate Oracle"] - (1 - matches["p1 opp service game win rate"])
matches["p2 relative return games Oracle"] = matches["p2 return game win rate Oracle"] - (1 - matches["p2 opp service game win rate"])

matches["p1 relative set Oracle"] = matches["p1 set win rate Oracle"] - (1 - matches["p1 opp set win rate"])
matches["p2 relative set Oracle"] = matches["p2 set win rate Oracle"] - (1 - matches["p2 opp set win rate"])

matches["p1 relative tiebreak Oracle"] = matches["p1 tiebreak win rate Oracle"] - (1 - matches["p1 opp tiebreak win rate"])
matches["p2 relative tiebreak Oracle"] = matches["p2 tiebreak win rate Oracle"] - (1 - matches["p2 opp tiebreak win rate"])

In [71]:
# Computing player-tournament stats
matches["p1 tourney serve adv Oracle"] = (matches["tourney serve win rate"] + matches["p1 relative serve Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p1 tourney return adv Oracle"] = (matches["tourney return win rate"] + matches["p1 relative return Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney serve adv Oracle"] = (matches["tourney serve win rate"] + matches["p2 relative serve Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney return adv Oracle"] = (matches["tourney return win rate"] + matches["p2 relative return Oracle"]).clip(upper=0.9985, lower=0.0015)

matches["p1 tourney service game adv Oracle"] = (matches["tourney service game win rate"] + matches["p1 relative service games Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p1 tourney return game adv Oracle"] = (matches["tourney return game win rate"] + matches["p1 relative return games Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney service game adv Oracle"] = (matches["tourney service game win rate"] + matches["p2 relative service games Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney return game adv Oracle"] = (matches["tourney return game win rate"] + matches["p2 relative return games Oracle"]).clip(upper=0.9985, lower=0.0015)

matches["p1 tourney set adv Oracle"] = (0.5 + matches["p1 relative set Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney set adv Oracle"] = (0.5 + matches["p2 relative set Oracle"]).clip(upper=0.9985, lower=0.0015)

matches["p1 tourney tiebreak adv Oracle"] = (0.5 + matches["p1 relative tiebreak Oracle"]).clip(upper=0.9985, lower=0.0015)
matches["p2 tourney tiebreak adv Oracle"] = (0.5 + matches["p2 relative tiebreak Oracle"]).clip(upper=0.9985, lower=0.0015)

In [72]:
# Computing matchup statistics
matchup_cols = ["p1 serve_tt", "p1 service_game_tt", "p1 set_tt", "p1 tiebreak_tt", "p2 serve_tt", "p2 service_game_tt"]
matches[matchup_cols] = matches.apply(lambda match: compute_matchup_stats_Oracle(match), axis=1, result_type="expand")

### Predict using $s_{ijtt}$ and $r_{ijtt}$

In [73]:
# Filter matches we want to predict on

# Only consider matches on or after August 1, 2012, because we've had one year of data at that point
games_after_2012 = matches[matches["date"] > datetime.strptime("01 Aug 12", '%d %b %y')]

# Only consider best of three set matches
games_after_2012 = games_after_2012[games_after_2012["tourney sets to win"] == 2]

# Don't consider Davis Cup matches because they don't have a final set tiebreak
games_after_2012 = games_after_2012[games_after_2012["tny_name"] != "DavisC"]

# Remove rows where either player hasn't played at least 10 matches in the past year
games_after_2012 = games_after_2012[(games_after_2012["p1 match count"] >= 2) & (games_after_2012["p2 match count"] >= 2)]

In [74]:
# Remove rows where we don't have s_ijtt values to predict the result of the match
games_after_2012 = games_after_2012[(games_after_2012['p1 serve_tt'].notna()) & (games_after_2012['p2 serve_tt'].notna())]

In [75]:
# compute Pr[p1 wins] with opponent/ tournament adjusted shrunken serve values
games_after_2012["p1 pr win"] = games_after_2012.apply(lambda match: match_driver(2, 6, 4, 7, 1, match["p1 serve_tt"], match["p2 serve_tt"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [76]:
# compute Pr[p1 wins] with non sos adjusted JS serve rates
games_after_2012["p1 pr win Oracle no sos adjust"] = games_after_2012.apply(lambda match: match_driver(2, 6, 4, 7, 1, match["p1 serve_tt Oracle no sos adjust"], match["p2 serve_tt Oracle no sos adjust"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [77]:
# compute log loss
games_after_2012["winner"] = games_after_2012["winner"].replace(2,0)

compute_lloss = games_after_2012[["winner", "p1 pr win", "p1 pr win Oracle no sos adjust"]]

compute_lloss["lloss sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win"]) + (1-m["winner"])*np.log(1 - m["p1 pr win"])), axis=1)
compute_lloss["lloss no sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win Oracle no sos adjust"]) + (1-m["winner"])*np.log(1 - m["p1 pr win Oracle no sos adjust"])), axis=1)
N = compute_lloss.shape[0]

lloss_sos_adjust = (compute_lloss["lloss sos adjust"].sum()) * (-1/N)
lloss_no_sos_adjust = (compute_lloss["lloss no sos adjust"].sum()) * (-1/N)

print(f"Sos adjust log loss: {lloss_sos_adjust}")
print(f"No sos adjust log loss: {lloss_no_sos_adjust}")
print(f"Random guessing log loss: {-np.log(0.5)}")

Sos adjust log loss: 0.6284688453159333
No sos adjust log loss: 0.635185342069233
Random guessing log loss: 0.6931471805599453

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

### Predict using $sg_{ijtt}$ and $rg_{ijtt}$ and $t_{ijtt}$

In [78]:
# Filter matches we want to predict on

# Only consider matches on or after August 1, 2012, because we've had one year of data at that point
games_after_2012 = matches[matches["date"] > datetime.strptime("01 Aug 12", '%d %b %y')]

# Only consider best of three set matches
games_after_2012 = games_after_2012[games_after_2012["tourney sets to win"] == 2]

# Don't consider Davis Cup matches because they don't have a final set tiebreak
games_after_2012 = games_after_2012[games_after_2012["tny_name"] != "DavisC"]

# Remove rows where either player hasn't played at least 10 matches in the past year
games_after_2012 = games_after_2012[(games_after_2012["p1 match count"] >= 2) & (games_after_2012["p2 match count"] >= 2)]

In [79]:
# Remove rows where we don't have sg_ijtt and t_ijtt values to predict the result of the match
games_after_2012 = games_after_2012[(games_after_2012['p1 service_game_tt'].notna()) & (games_after_2012['p2 service_game_tt'].notna()) & (games_after_2012['p1 tiebreak_tt'].notna())]

In [80]:

# compute Pr[p1 wins] with non opponenent/ tournament adjusted service game values
games_after_2012["p1 pr win opp adjust game based"] = games_after_2012.apply(lambda match: match_driver_game_based(2, 6, 4, 7, 1, match["p1 service_game_tt"], match["p2 service_game_tt"], match["p1 tiebreak_tt"]), axis=1).clip(upper=0.9985, lower=0.0015)
games_after_2012["p1 pr win Oracle no sos adjust game based"] = games_after_2012.apply(lambda match: match_driver_game_based(2, 6, 4, 7, 1, match["p1 service_game_tt Oracle no sos adjust"], match["p2 service_game_tt Oracle no sos adjust"], match["p1 tiebreak_tt Oracle no sos adjust"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [81]:
games_after_2012["winner"] = games_after_2012["winner"].replace(2,0)

compute_lloss = games_after_2012[["winner", "p1 pr win opp adjust game based", "p1 pr win Oracle no sos adjust game based"]]

compute_lloss["lloss sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win opp adjust game based"]) + (1-m["winner"])*np.log(1 - m["p1 pr win opp adjust game based"])), axis=1)
compute_lloss["lloss Oracle no sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win Oracle no sos adjust game based"]) + (1-m["winner"])*np.log(1 - m["p1 pr win Oracle no sos adjust game based"])), axis=1)
N = compute_lloss.shape[0]

lloss_sos_adjust = (compute_lloss["lloss sos adjust"].sum()) * (-1/N)
lloss_no_sos_adjust = (compute_lloss["lloss Oracle no sos adjust"].sum()) * (-1/N)

print(f"Sos adjust log loss: {lloss_sos_adjust}")
print(f"No sos adjust log loss: {lloss_no_sos_adjust}")
print(f"Random guessing log loss: {-np.log(0.5)}")

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

Sos adjust log loss: 0.6215389477581559
No sos adjust log loss: 0.6396465011377351
Random guessing log loss: 0.6931471805599453

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Try to predict games using $sets_{ijtt}$ values

In [82]:
# Filter matches we want to predict on

# Only consider matches on or after August 1, 2012, because we've had one year of data at that point
games_after_2012 = matches[matches["date"] > datetime.strptime("01 Aug 12", '%d %b %y')]

# Only consider best of three set matches
games_after_2012 = games_after_2012[games_after_2012["tourney sets to win"] == 2]

# Don't consider Davis Cup matches because they don't have a final set tiebreak
games_after_2012 = games_after_2012[games_after_2012["tny_name"] != "DavisC"]

# Remove rows where either player hasn't played at least 10 matches in the past year
games_after_2012 = games_after_2012[(games_after_2012["p1 match count"] >= 2) & (games_after_2012["p2 match count"] >= 2)]

In [83]:
# Remove rows where we don't have sg_ijtt and t_ijtt values to predict the result of the match
games_after_2012 = games_after_2012[(games_after_2012['p1 set_tt'].notna())]

In [84]:

# compute Pr[p1 wins] with non opponenent/ tournament adjusted service game values
games_after_2012["p1 pr win opp adjust set based"] = games_after_2012.apply(lambda match: match_driver_set_based(2, match["p1 set_tt"]), axis=1).clip(upper=0.9985, lower=0.0015)
games_after_2012["p1 pr win Oracle no sos adjust set based"] = games_after_2012.apply(lambda match: match_driver_set_based(2, match["p1 set_tt Oracle no sos adjust"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [85]:
games_after_2012["winner"] = games_after_2012["winner"].replace(2,0)

compute_lloss = games_after_2012[["winner", "p1 pr win opp adjust set based", "p1 pr win Oracle no sos adjust set based"]]

compute_lloss["lloss sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win opp adjust set based"]) + (1-m["winner"])*np.log(1 - m["p1 pr win opp adjust set based"])), axis=1)
compute_lloss["lloss no sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win Oracle no sos adjust set based"]) + (1-m["winner"])*np.log(1 - m["p1 pr win Oracle no sos adjust set based"])), axis=1)
N = compute_lloss.shape[0]

lloss_sos_adjust = (compute_lloss["lloss sos adjust"].sum()) * (-1/N)
lloss_no_sos_adjust = (compute_lloss["lloss no sos adjust"].sum()) * (-1/N)

print(f"Sos adjust log loss: {lloss_sos_adjust}")
print(f"No sos adjust log loss: {lloss_no_sos_adjust}")
print(f"Random guessing log loss: {-np.log(0.5)}")

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

Sos adjust log loss: 0.6204046636708702
No sos adjust log loss: 0.6328733127769348
Random guessing log loss: 0.6931471805599453

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Try to predict using $sg_{ijtt}$ for games and $s_{ijtt}, s_{jitt}$ for tiebreaks

In [86]:
# Filter matches we want to predict on

# Only consider matches on or after August 1, 2012, because we've had one year of data at that point
games_after_2012 = matches[matches["date"] > datetime.strptime("01 Aug 12", '%d %b %y')]

# Only consider best of three set matches
games_after_2012 = games_after_2012[games_after_2012["tourney sets to win"] == 2]

# Don't consider Davis Cup matches because they don't have a final set tiebreak
games_after_2012 = games_after_2012[games_after_2012["tny_name"] != "DavisC"]

# Remove rows where either player hasn't played at least 10 matches in the past year
games_after_2012 = games_after_2012[(games_after_2012["p1 match count"] >= 2) & (games_after_2012["p2 match count"] >= 2)]

In [87]:
# Remove rows where we don't have sg_ijtt and s_ijtt values to predict the result of the match
games_after_2012 = games_after_2012[(games_after_2012['p1 service_game_tt'].notna()) & (games_after_2012['p2 service_game_tt'].notna()) & (games_after_2012['p1 serve_tt'].notna()) & (games_after_2012['p2 serve_tt'].notna())]

In [88]:
# compute Pr[p1 wins] with non opponenent/ tournament adjusted service game values
games_after_2012["p1 pr win opp adjust mix"] = games_after_2012.apply(lambda match: match_driver_game_based_tiebreak_serve_based(2, 6, 4, 7, 1, match["p1 service_game_tt"], match["p2 service_game_tt"], match["p1 serve_tt"], match["p2 serve_tt"]), axis=1).clip(upper=0.9985, lower=0.0015)
games_after_2012["p1 pr win Oracle no sos adjust mix"] = games_after_2012.apply(lambda match: match_driver_game_based_tiebreak_serve_based(2, 6, 4, 7, 1, match["p1 service_game_tt Oracle no sos adjust"], match["p2 service_game_tt Oracle no sos adjust"], match["p1 serve_tt Oracle no sos adjust"], match["p2 serve_tt Oracle no sos adjust"]), axis=1).clip(upper=0.9985, lower=0.0015)

In [89]:
games_after_2012["winner"] = games_after_2012["winner"].replace(2,0)

compute_lloss = games_after_2012[["winner", "p1 pr win opp adjust mix", "p1 pr win Oracle no sos adjust mix"]]

compute_lloss["lloss sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win opp adjust mix"]) + (1-m["winner"])*np.log(1 - m["p1 pr win opp adjust mix"])), axis=1)
compute_lloss["lloss no sos adjust"] = compute_lloss.apply(lambda m: (m["winner"]*np.log(m["p1 pr win Oracle no sos adjust mix"]) + (1-m["winner"])*np.log(1 - m["p1 pr win Oracle no sos adjust mix"])), axis=1)
N = compute_lloss.shape[0]

lloss_sos_adjust = (compute_lloss["lloss sos adjust"].sum()) * (-1/N)
lloss_no_sos_adjust = (compute_lloss["lloss no sos adjust"].sum()) * (-1/N)

print(f"Sos adjust log loss: {lloss_sos_adjust}")
print(f"No sos adjust log loss: {lloss_no_sos_adjust}")
print(f"Random guessing log loss: {-np.log(0.5)}")

Sos adjust log loss: 0.6177242177178989
No sos adjust log loss: 0.633204284420476
Random guessing log loss: 0.6931471805599453

/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/VillasBoas/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [5]:
sigma=3
d = 5
tao = 10

In [23]:
from scipy.optimize import fsolve
import numpy as np

def compute_l1_norm_minus_constraint(alpha, theta, gamma,penal):
    return np.linalg.norm(theta + alpha*gamma, ord=1) - penal

theta = np.array([0.5,1,-5,3])
gamma = np.array([0,7.1,-1.3,0.25])
alpha_0 = 2
penal = 20
alpha = fsolve(compute_l1_norm_minus_constraint, x0=alpha_0, args = (theta,gamma,penal))

In [24]:
np.linalg.norm(theta + alpha*gamma, ord=1) - penal

3.552713678800501e-15

In [25]:
alpha

array([1.21387283])

In [95]:
matches[["p1 year tiebreak total", "p2 year tiebreak total"]].describe()

       p1 year tiebreak total  p2 year tiebreak total
count            10787.000000            10787.000000
mean                17.602206               15.977751
std                 12.412893               11.473495
min                  2.000000                2.000000
25%                  7.000000                6.000000
50%                 16.000000               14.000000
75%                 26.000000               23.000000
max                 73.000000               75.000000

In [94]:
matches

,pbp_id,date,tny_name,tour,draw,server1,server2,winner,pbp,score,adf_flag,wh_minutes,p1 serves won,p1 serves total,p1 service games won,p1 service games total,p1 sets won,p1 tiebreaks won,p2 serves won,p2 serves total,p2 service games won,p2 service games total,p2 sets won,p2 tiebreaks won,sets total,tourney serves won,tourney serves total,tourney service games won,tourney service games total,p1 serve win rate,p1 return win rate,p1 service game win rate,p1 return game win rate,p1 set win rate,p1 tiebreak win rate,p2 serve win rate,p2 return win rate,p2 service game win rate,p2 return game win rate,p2 set win rate,p2 tiebreak win rate,p1 opp serve win rate,p1 opp return win rate,p1 opp service game win rate,p1 opp return game win rate,p1 opp set win rate,p1 opp tiebreak win rate,p2 opp serve win rate,p2 opp return win rate,p2 opp service game win rate,p2 opp return game win rate,p2 opp set win rate,p2 opp tiebreak win rate,p1 match count,p2 match count,all player year serve win rate,all player year service game win rate,p1 year serve total,p1 year return total,p1 year service game total,p1 year return game total,p1 year set total,p1 year tiebreak total,p2 year serve total,p2 year return total,p2 year service game total,p2 year return game total,p2 year set total,p2 year tiebreak total,p1 year match win rate,p2 year match rate,p1 year match results,p2 year match results,p1 opp match win rate,p2 opp match win rate,tourney sets to win,tourney serve win rate,tourney return win rate,tourney service game win rate,tourney return game win rate,p1 serve win rate variance,p1 return win rate variance,p1 service game win rate variance,p1 return game win rate variance,p1 set win rate variance,p1 tiebreak win rate variance,p2 serve win rate variance,p2 return win rate variance,p2 service game win rate variance,p2 return game win rate variance,p2 set win rate variance,p2 tiebreak win rate variance,all player serve win rate variance,all player return win rate variance,all player service game win rate variance,all player return game win rate variance,all player set win rate variance,all player tiebreak win rate variance,p1 serve win rate variance2,p1 return win rate variance2,p1 service game win rate variance2,p1 return game win rate variance2,p1 set win rate variance2,p1 tiebreak win rate variance2,p2 serve win rate variance2,p2 return win rate variance2,p2 service game win rate variance2,p2 return game win rate variance2,p2 set win rate variance2,p2 tiebreak win rate variance2,all player serve win rate variance2,all player return win rate variance2,all player service game win rate variance2,all player return game win rate variance2,all player set win rate variance2,all player tiebreak win rate variance2,all player serve win rate variance3,all player return win rate variance3,all player service game win rate variance3,all player return game win rate variance3,all player set win rate variance3,all player tiebreak win rate variance3,p1 oracle coef serve,p1 oracle coef return,p1 oracle coef service game,p1 oracle coef return game,p1 oracle coef set,p1 oracle coef tiebreak,p2 oracle coef serve,p2 oracle coef return,p2 oracle coef service game,p2 oracle coef return game,p2 oracle coef set,p2 oracle coef tiebreak,p1 oracle coef serve2,p1 oracle coef return2,p1 oracle coef service game2,p1 oracle coef return game2,p1 oracle coef set2,p1 oracle coef tiebreak2,p2 oracle coef serve2,p2 oracle coef return2,p2 oracle coef service game2,p2 oracle coef return game2,p2 oracle coef set2,p2 oracle coef tiebreak2,p1 serve win rate Oracle,p1 return win rate Oracle,p1 service game win rate Oracle,p1 return game win rate Oracle,p1 set win rate Oracle,p1 tiebreak win rate Oracle,p2 serve win rate Oracle,p2 return win rate Oracle,p2 service game win rate Oracle,p2 return game win rate Oracle,p2 set win rate Oracle,p2 tiebreak win rate Oracle,p1 serve_tt Oracle no sos adjust,p2 serve_tt JS no sos adjust,p1 service_game_tt Oracle no sos adjust,p2 service_game_tt Oracle no sos adjust,p1 tiebreak_tt Oracle no sos adjust,p1 set_tt Oracle no sos adjust,p1 relative serve Oracle,p2 relative serve Oracle,p1 relative return Oracle,p2 relative return Oracle,p1 relative service games Oracle,p2 relative service games Oracle,p1 relative return games Oracle,p2 relative return games Oracle,p1 relative set Oracle,p2 relative set Oracle,p1 relative tiebreak Oracle,p2 relative tiebreak Oracle,p1 tourney serve adv Oracle,p1 tourney return adv Oracle,p2 tourney serve adv Oracle,p2 tourney return adv Oracle,p1 tourney service game adv Oracle,p1 tourney return game adv Oracle,p2 tourney service game adv Oracle,p2 tourney return game adv Oracle,p1 tourney set adv Oracle,p2 tourney set adv Oracle,p1 tourney tiebreak adv Oracle,p2 tourney tiebreak adv Oracle,p1 serve_tt,p1 service_game_tt,p1 set_tt,p1 tiebreak_tt,p2 serve_tt,p2 service_game_tt,p2 serve_tt Oracle no sos adjust
0,2231275,2011-07-28,ATPStu,ATP,Main,Olivier Rochus,Fabio Fognini,2,SSSS;RRRR;SSRRSS;SSRRSS;RSRSRSRR;SSRSS;RSRRSR;...,6-4 6-1,0,66,27,58,3,9,0,0,32,56,6,8,2,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2231276,2011-07-28,ATPStu,ATP,Main,Robin Haase,Marin Cilic,2,SSRSS;RRSSRSSS;SSSS;RSSSS;SRSRSS;RSRSRSSS;RSRS...,4-6 6-4 6-3,0,141,60,102,11,15,1,0,60,92,12,14,2,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2231342,2011-07-28,Farmer,ATP,Main,Alejandro Falla,Thomaz Bellucci,2,SRRSSRSRRSRSRSRSRSRR;SSSRS;RRSRR;SRSSS;RRSSRR;...,6-0 6-1,0,42,21,55,1,7,0,0,26,37,6,6,2,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2229262,2011-07-28,Credit,ATP,Main,Matthias Bachinger,Julien Benneteau,2,SSSS;SSSS;RRRR;SSSS;SSSS;SRRRSSRSSRRSSRSS;SSSS...,6-4 6-4,0,57,36,59,7,10,0,0,43,58,9,10,2,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2228887,2011-07-28,Credit,ATP,Main,Stan Wawrinka,Peter Luczak,1,SSSS;RRSSSS;SRSSRS;RRSSSS;SSSRS;SSSRRS;RSSSS;R...,6-3 7-5,0,82,43,58,10,11,2,0,34,61,7,10,0,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0,0,2,2,2,2,0,0,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,0.125000,0.125000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10782,8628374,2015-12-18,Men'sAustralianOpenWildCardPlayoff,ATP,Main,James Duckworth,Marinko Matosevic,1,SSSS;RSRSRSSS;SSSS;RSSRSS;SRSRRSRR;SRRRSSRR;SS...,4-6 6-3 7-6(7) 7-6(8),0,199,103,154,18,22,3,2,93,146,17,21,1,0,4,564.0,879.0,112.0,147.0,0.635690,0.335260,0.792208,0.169935,0.477612,0.500000,0.575717,0.348559,0.685345,0.188034,0.301887,0.142857,0.625203,0.364778,0.758255,0.178435,0.414046,0.454246,0.629896,0.374191,0.766704,0.191251,0.436469,0.379723,21,19,0.641567,0.797852,2023,1903,308,306,67,20,1499,1423,232,234,53,7,0.210526,0.575717,WWLWLWLWLWWLLWLWLLLLW,LLWLLWLWLLLLLLLLLLW,0.40433,0.450411,3,0.641638,0.358362,0.761905,0.238095,0.000264,0.000194,0.000930,0.000713,0.004855,0.013125,0.000343,0.000301,0.001951,0.000855,0.006920,0.007144,0.000011,0.000009,0.000032,0.00003,0.000144,0.000136,0.000114,0.000121,0.000524,0.000527,0.003731,0.012500,0.000153,0.000162,0.000695,0.000689,0.004717,0.035714,0.005356,0.003533,0.023770,0.009697,0.072589,0.086436,0.003544,0.002968,0.010231,0.009499,0.045352,0.030022,0.884343,0.265448,0.966873,0.407155,0.906420,1.000000,0.073319,0.755352,0.133551,0.811084,0.149881,0.053038,0.766909,0.183702,0.942650,0.336838,0.881579,1.00,0.034169,0.623747,0.052062,0.775792,0.107287,0.21875,0.640197,0.339517,0.797528,0.180785,0.497349,0.500000,0.577967,0.354718,0.691202,0.198983,0.323142,0.220982,0.763973,0.727510,0.940676,0.910257,0.779018,0.674534,0.004975,-0.047842,-0.035280,-0.015386,-0.024037,-0.117547,-0.060960,-0.034313,-0.088605,-0.240389,-0.045754,-0.399295,0.646613,0.323082,0.593796,0.342976,0.737868,0.177136,0.644358,0.203783,0.411395,0.259611,0.454246,0.100705,0.778034,0.916655,0.665920,0.881414,0.753864,0.893805,0.727085
10783,8625517,2015-12-18,Men'sS,ATP,Main,Jesse Huta Galung,Matwe Middelkoop,2,SSRSS;RSSSS;RRRSSR;RRRR;RRSRR;SSRRSRSS;SSRRSS;...,6-4 6-3,0,70,31,54,6,10,0,0,41,65,8,9,2,0,2,461.0,771.0,87.0,124.0,0.621951,0.313187,0.724138,0.100000,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.700937,0.346911,0.829079,0.221165,0.564946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,0.641567,0.797852,164,182,29,30,8,2,0,0,2,2,2,2,NaN,NaN,LL,NaN,NaN,NaN,2,0.597925,0.402075,0.701613,0.298387,0.003110,0.004991,0.000862,0.005156,0.019531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000011,0.000009,0.000032,0.00003,0.000144,0.000136,0.001402,0.001264,0.005562,0.005376,0.031250,0.125000,NaN,NaN,0.080642,0.080642,0.125000,0.125000,0.005356,0.003533,0.023770,0.009697,0.072589,0.086436,0.003544,0.002968,0.010231,0.009499,0.045352,0.030022,0.889905,0.709113,0.136980,0.330702,0.238095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.784668,0.381645,0.505809,0.340040,0.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.637343,0.330455,0.761423,0.134734,0.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.015746,NaN,0.031391,NaN,-0.017412,NaN,-0.036187,NaN,-0.101721,NaN,NaN,NaN,0.582179,0.433467,NaN,NaN,0.684201,0.262200,NaN,NaN,0.398279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10784,8625520,2015-12-18,Men'sS,ATP,Main,Tallon Griekspoor,Robin Haase,2,SSSRS;SSSRRRSS;RSRSSRRR;RSSSS;SRSRRR;SSSRS;SRS...,6-2 6-3,0,63,38,71,5,9,0,0,35,47,8,8,2,0,2,461.0,771.0,87.0,124.0,0.666667,0.520000,0.800000,0.600000,0.750000,NaN,0.622655,0.342847,0.771739,0.186296,0.444444,0.500000,0.480000,0.340000,0.320000,0.160000,0.125000,NaN,0.640685,0.360862,0.791987,0.194391,0.488360,0.409366,1,34,0.641567,0.797852,51,50,10,10,4,2,2878,2838,460,467,99,16,0.411765,0.622655,W,LLLLLLWWLWLLWWLLWWWLWLLWWLLLWLWWLL,NaN,0.484743,2,0.597925,0.402075,0.701613,0.298387,0.226667,0.254694,0.131429,0.268571,0.125000,NaN,0.000141,0.000139,0.000579,0.000439,0.002856,NaN,0.000011,0.000009,0.000032,0.00003,0.000144,0.000136,0.004509,0.004599,0.016128,0.016128,0.062500,0.125000,0.000080,0.000081,0.000351,0.000345,0.002525,0.015625,0.005356,0.003533,0.023770,0.009697,0.072589,0.086436,0.003544,0.002968,0.010231,0.009499,0.045352,0.030022,0.997228,0.907036,0.999965,0.629183,0.666667,NaN,0.283311,0.363972,0.459320,0.635741,0.480653,NaN,0.877413,0.149795,0.999714,0.092472,0.500000,NaN,0.182594,0.250137,0.339579,0.578825,0.450000,1.00000,0.644644,0.495798,0.797853,0.563210,0.625000,NaN,0.626108,0.346746,0.780607,0.195471,0.469444,0.500000,0.773636,0.739069,0.942011,0.733998,NaN,0.653215,-0.015356,-0.013030,-0.024202,-0.012569,-0.042147,-0.025003,-0.116790,-0.012542,-0.250000,-0.042195,NaN,-0.090634,0.582569,0.377873,0.584895,0.389506,0.659466,0.181597,0.676610,0.285845,0.250000,0.457805,NaN,0.409366,0.686265,0.828717,0.283040,NaN,0.698778,0.904115,0.630034
10785,8632913,2015-12-19,Men'sS,ATP,Main,Jasper Smit,Matwe Middelkoop,2,SRRRR;SSSS;SRRSSS;RRRSSSSS;RSSSS;RRRSR;SRRSRSR...,6-4 6-7(6) 6-3,0,109,62,93,12,15,1,1,68,98,15,16,2,0,3,606.0,1008.0,114.0,160.0,0.675676,0.411111,0.733333,0.333333,0.600000,NaN,0.630769,0.425926,0.818182,0.416667,0.750000,NaN,0.627586,0.314379,0.624000,0.277333,0.342857,NaN,0.610092,0.394737,0.566434,0.076923,0.100000,NaN,1,1,0.641537,0.797829,74,90,15,15,5,2,65,54,11,12,4,2,1.000000,0.630769,W,W,NaN,NaN,2,0.601190,0.398810,0.712500,0.287500,0.222140,0.244819,0.193704,0.231481,0.000000,NaN,0.236538,0.249126,0.116736,0.266975,0.125000,NaN,0.000011,0.000009,0.000032,0.00003,0.000143,0.000136,0.003108,0.002555,0.010753,0.010753,0.050000,0.125000,0.003538,0.004259,0.014663,0.013442,0.062500,0.125000,0.005328,0.003424,0.023732,0.009069,0.072363,0.085721,0.003543,0.002963,0.010226,0.009491,0.045366,0.030110,0.994781,0.988805,0.978977,0.930822,0.000000,NaN,0.999510,0.982059,0.996464,0.853001,0.666667,NaN,0.727260,0.479667,0.721069,0.384638,0.833333,NaN,0.968268,0.483394,0.972526,0.226098,0.500000,NaN,0.650848,0.385858,0.779839,0.282883,0.516667,NaN,0.641195,0.393315,0.798388,0.368170,0.625000,NaN,0.741958,0.761605,0.858733,0.909410,NaN,0.390756,-0.034773,0.035932,0.013444,0.003406,0.057172,-0.124689,-0.093117,-0.065397,-0.140476,-0.275000,NaN,NaN,0.566418,0.412253,0.637123,0.402216,0.769672,0.194383,0.587811,0.222103,0.359524,0.225000,NaN,NaN,0.660044,0.921283,0.659110,NaN,0.714544,0.855289,0.739874
10786,8634739,2015-12-20,Men'sS,ATP,Main,Matwe Middelkoop,Robin Haase,2,SSSS;SSSS;SRRSRSSS;SSRRRSRSSS;SSRSRS;SRSSS;RSS...,7-6(4) 2-6 7-5,0,121,63,97,13,16,1,0,69,112,12,16,2,1,3,736.0,1199.0,141.0,191.0,0.668712,0.367347,0.888889,0.296296,0.714286,0.333333,0.624615,0.345823,0.775641,0.191176,0.455446,0.500000,0.646506,0.382594,0.685090,0.148883,0.271429,0.222222,0.639874,0.358384,0.790144,0.196318,0.488591,0.409366,2,35,0.641555,0.797863,163,147,27,27,7,3,2925,2909,468,476,101,16,0.428571,0.624615,WW,LLLLLLWWLWLLWWLLWWWLWLLWWLLLWLWWLLW,0.25000,0.485179,2,0.613845,0.386155,0.738220,0.261780,0.000916,0.001852,0.001660,0.008675,0.014161,0.024691,0.000140,0.000140,0.000572,0.000446,0.002859,0.010723,0.000011,0.000009,0.000032,0.00003,0.000143,0.000136,0.001411,0.001564,0.005973,0.005973,0.035714,0.083333,0.000079,0.000079,0.000345,0.000339,0.002475,0.015625,0.005330,0.003400,0.023756,0.008930,0.071769,0.087201,0.003538,0.002961,0.010213,0.009484,0.045328,0.030350,0.553903,0.958974,0.166876,0.494542,0.235702,0.470588,0.328162,0.468495,0.536737,0.787802,0.590163,1.000000,0.656709,0.951788,0.418912,0.402530,0.437500,0.75,0.215063,0.331645,0.411017,0.738249,0.554945,1.00000,0.650878,0.358874,0.850757,0.258394,0.620536,0.458333,0.628258,0.350009,0.784775,0.199268,0.480171,0.500000,0.775894,0.752780,0.958171,0.912778,0.458333,0.639036,0.033472,-0.013358,0.005381,-0.010117,-0.000360,-0.018908,-0.056515,-0.010588,-0.108036,-0.031238,-0.319444,-0.090634,0.647316,0.391536,0.600487,0.376038,0.737860,0.205265,0.719312,0.251193,0.391964,0.468762,0.180556,0.409366,0.752811,0.893513,0.422152,0.241220,0.700222,0.908442,0.751197